### ISSUE TITLE
apt-get install realpath fails on bionic

### ISSUE THREAD

**Issue by awlodarkiewicz** [adshares/ads-tools#1]
On 18.04 the following command fails:

apt-get install realpath python
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Package realpath is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
 manpages-pl manpages-fr-extra

E: Package 'realpath' has no installation candidate

**Comment by m-pilarczyk** [comment]
Replace `realpath` with `readlink`

**Comment by Manvi07** [comment]
Still showing `E: Unable to locate package readlink`
